---
title: "Untitled"
output: html_document
date: "2025-09-16"
---


  Run this script first `health-modeling-zonal-stats.ipynb` to update the input data for viz.


```{r setup, include=FALSE}

# # To clear your environment 
# remove(list = ls())


library(here)
library(readr)
library(sf)
library(dplyr)
library(stringr)
library(ggplot2)

theme_set(theme_bw(base_size = 11))

ymd   <- format(Sys.time(), "%Y%m%d"); ymd


dir.fig <- "G:/Shared drives/Wellcome Trust Project Data/3_final/UCM_figures"

source(here('code', 'func_ggsave.R'))
source(here('code', 'func_get_color_scale.R'))
```

## Data

### CVS data from zonal stats

```{r - help data}
dir_ucm_out <- 'G:/Shared drives/Wellcome Trust Project Data/2_postprocess_intermediate/UCM_official_runs'


## load `aoi` in sf
f <- file.path(dir_ucm_out, 'ucm_output_postprocess', 'aoi_sf.rds')
aoi <- readRDS(f)
```


```{r - which health data?}

ind_label <- 'Mortality'


## load data 
## --> update this input data
f <- file.path(dir_ucm_out, 'health_output_stats', 'health_london_18_zonal_stats_long.csv'); post_fix <- '00_2021_2050'; 
f <- file.path(dir_ucm_out, 'health_output_stats', 'health_london_18_zonal_stats_long_2050_2050.csv'); post_fix <- 'i0_2050_2050'

df <- read_csv(f, show_col_types = F) %>%
  mutate(
    indicator = gsub('\\.tif|Excess_', '', raster),
    lc_scenario = gsub('health_output_', '', lc_scenario),
    lc_scenario = gsub('_2050', '', lc_scenario),
    indicator = ifelse(indicator == 'self_harm', "suicide", indicator),
    indicator = str_to_title(indicator)
  ) %>%
  
  # mutate(climate = str_extract(raster, "\\d+deg_\\d+uhi")) %>%
  # mutate(
  #    climate = case_when(
  #      indicator < 2030 ~ 'current',
  #      T ~ 'future'
  #    )
  #    ) %>%
  ## re-code: change scenario-3 (tree risk) as scenario-2
  mutate(
    lc_scenario = gsub('s0_', '', lc_scenario),
    lc_scenario = case_when(
      lc_scenario == 's1'  ~ 'scenario1',
      lc_scenario == 's2'  ~ 'scenario3_TO',
      lc_scenario == 's3'  ~ 'scenario2_TR',
      lc_scenario == 's41' ~ 'scenario4_10',
      lc_scenario == 's42' ~ 'scenario4_20',
      lc_scenario == 's43' ~ 'scenario4_30',
      TRUE                 ~ NA_character_
    ) 
  ) %>%
  rename('cases' = 'sum')



## add sf 
df_sf <- df %>%
  select(GSS_CODE, 
         # year, 
         indicator, lc_scenario, cases) %>%
  mutate(var = indicator) %>%
  left_join(aoi, ., by = 'GSS_CODE')


##' save a copy for viz
##'   Here, we only save the change attributable to land use change
if(post_fix == 'i0_2050_2050') {
  
  ## save a copy for viz
  f <- here('data', paste0('viz_sf_', ind_label, '_lc_effect.rds')); print(f)
  # "./data/viz_sf_avg_hvpd_v_lc_effect.rds"
  saveRDS(df_sf, f)
}
```


## Viz

```{r - data stats - average case across borough}
str(df)

# Example summarisation (if df has replicates per group)
df_summary <- df %>%
  select(-raster) %>%
  as.data.frame() %>%
  group_by(lc_scenario, indicator) %>%
  # dplyr::group_by(lc_scenario, climate) %>%
  dplyr::summarise(
    mean = mean(cases, na.rm = TRUE),          # group mean
    sd   = sd(cases, na.rm = TRUE),            # standard deviation
    n    = n(),                                # sample size
    se   = sd / sqrt(n),                       # standard error
    ci_lower = mean - 1.96 * se,
    ci_upper = mean + 1.96 * se, 
    .groups = "drop"
  )
```


```{r - bar plot}

# Bar plot with error bars

df_summary %>%
  ggplot(., aes(x = lc_scenario, y = mean)) +
  geom_col(position = position_dodge(width = 0.9), alpha = 0.5) +
  geom_errorbar(
    # aes(ymin = mean - sd, ymax = mean + sd),
    aes(ymin = ci_lower, ymax = ci_upper),
    width = 0.2, alpha = 0.5, 
    position = position_dodge(width = 0.9)
  ) +
  
  # add mean values as text labels
  geom_text(
    aes(label = round(mean, 1), y = mean),   # label from mean
    vjust = -0.5,                            # push above bar
    size = 4, color = 'red'                  # adjust font size
  ) +
  
  facet_wrap(~ indicator) + # , scale = 'free_y'
  # facet_wrap(~ indicator, scale = 'free_y') + #
  labs(
    x = "Land Use Scenario",
    y = "Average Mortality by borough",
    # fill = "indicator"
  ) +
  # scale_fill_brewer(palette = "Set2", direction = 1) +  # reverse order
  theme_bw() +
  # coord_cartesian(ylim = c(20, NA)) +   # start at 20, let top auto-scale
  scale_y_continuous(expand = c(0, 1)) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )


# Save your last ggplot as PNG
f <- file.path(dir.fig, paste0("health_scenarios_fromRaster_",post_fix, '_', ymd, ".png"))
ggsave(
  filename = f, 
  width    = 7,                    # width in inches
  height   = 5,                    # height in inches
  units = 'in',
  dpi      = 300                   # resolution (good for PPT/publications)
)

```


```{r - map, eval=FALSE, include=FALSE}

data <- df_sf %>%
  rename(value_diff = cases) %>%
  mutate(var = factor(var, levels = rev(unique(var))))

library(ggh4x)
p <- ggplot(data = data) +
  geom_sf(aes(fill = value_diff), color = NA, size = 0.1) + 
  facet_grid(lc_scenario~var, switch = "y") +
  # facet_wrap(~ var + lc_scenario, scales = "free") +
  # facet_grid2(var ~ lc_scenario, scales = "free", independent = "all") + 
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    strip.text = element_text(size = 10, face = "bold"),
    strip.text.y.left = element_text(
      angle = 45, 
      margin = margin(l = 6, r = 4), # Tip: if labels clip, add a little space
      hjust = 0.5, vjust = 0.5),
    legend.position = "right",
    legend.key.width = unit(.5, "cm")
  ) +
  labs(
    title = paste("Change in", ind_label, 'from baseline'),
  )

print(p)


# f <- file.path(dir.fig, paste0("health_scenarios_fromRaster_", "map_dif_", ymd, ".png"))
# print(f)
# func_ggsave(f, w = 7, h = 7, dpi = 500, save_png = T)
```




```{r - map - dif scale}

library(ggnewscale)
library(purrr)

data <- df_sf %>%
  rename(value_diff = cases) %>%
  mutate(var = factor(var, levels = rev(unique(var))))


value_min <- min(data$value_diff, na.rm = T)


# Split data by var and create separate layers
vars <- levels(data$var)

# Define specific palettes for each var
var_palettes <- list(
  Cardiovascular = c("#fff5eb", "#fee6ce", "#fdd0a2", "#fdae6b", "#fd8d3c", "#f16913", "#d94801", "#a63603", "#7f2704"),
  Respiratory    = c("#f7fbff", "#deebf7", "#c6dbef", "#9ecae1", "#6baed6", "#4292c6", "#2171b5", "#08519c", "#08306b"),
  Suicide        = c("#fcfbfd", "#efedf5", "#dadaeb", "#bcbddc", "#9e9ac8", "#807dba", "#6a51a3", "#54278f", "#3f007d")
)


p <- ggplot()

for (v in vars) {
  data_subset <- data %>% filter(var == v)
  scale_params <- get_color_scale(data_subset$value_diff)
  
  ## change color plate
  if( value_min >=0){
    scale_params$colors <- var_palettes[[v]]
    ## for cases there are both negative and positive values
  } else {
    scale_params$colors <- rev(c("#d7191c", "#ffffbf", "#2c7bb6"))
  }
  
  
  p <- p +
    geom_sf(data = data_subset, 
            aes(fill = value_diff), 
            color = NA, size = 0.1) +
    scale_fill_gradientn(
      colors = scale_params$colors,
      limits = c(scale_params$vmin, scale_params$vmax),
      name = "Change",
      # labels = scales::label_number(accuracy = 0.1),  # 1 decimal place
      guide = guide_colorbar(
        title = v,
        title.position = "top",      # 标题在上方
        title.hjust = 0.5,           # 标题居中
        order = which(vars == v)  # This helps ensure order
        )
    ) +
    new_scale_fill()
}

p <- p +
  facet_grid(var ~ lc_scenario, switch = "y") +
  theme_minimal(base_size = 10) +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    strip.text = element_text(face = "bold"),
    strip.text.y.left = element_text(
      angle = 45, 
      margin = margin(l = 10, r = 4), # Tip: if labels clip, add a little space
      hjust = 0.5, vjust = 0.5),
    strip.clip = "off",  # avoid text being clipped
    legend.position = "bottom",
    legend.box = "horizontal",
    legend.text = element_text(angle = 45, vjust = 1, hjust = 1),
    legend.key.width = unit(0.6, "cm"),
    legend.key.height = unit(0.2, "cm")
  )


p

f <- file.path(dir.fig, paste0("health_scenarios_fromRaster_", "map_dif_scale_", post_fix, '_', ymd, ".png"))
print(f)
func_ggsave(f, w = 7, h = 3.5, unit = 'in', dpi = 300, save_png = T)
```


```{r}

# library(tmap)
# 
# tm_shape(data) +
#   tm_polygons(
#     "value_diff",
#     fill.scale = tm_scale_continuous(
#       values = "brewer.rd_bu",
#       midpoint = 0
#     ),
#     fill.free = TRUE
# ) +
#   tm_facets_grid(
#     rows = "var",
#     columns = "lc_scenario",
#   ) +
#   tm_layout(legend.outside = TRUE)


```




