---
title: "Untitled"
output: html_document
date: "2025-09-26"
---

```{r setup, include=FALSE}

# # To clear your environment 
# remove(list = ls())

library(readr)
library(dplyr)
library(tidyr)
library(purrr)
library(stringr)
library(ggplot2)

theme_set(theme_bw(base_size = 11))

ymd   <- format(Sys.time(), "%Y%m%d"); ymd


dir_main <- "G:/Shared drives/Wellcome Trust Project Data"
dir_fig <- file.path(dir_main, "3_final/UCM_figures")

```

## total by cause - city-level

```{r}
# --- paths ---
dir_data = file.path(dir_main, "2_postprocess_intermediate/UCM_official_runs")



# --- load & reshape ---

# f_draws <- file.path(dir_data, "health_output_s0_s3", "city_total_draws_by_cause.csv")
# # Scenario <- str_extract(f_draws, "s\\d+_s\\d+(?=/|$)"); Scenario
# df <- read_csv(f_draws, show_col_types = FALSE)
# causes <- setdiff(names(df), "draw")


## - batch 
fs <- list.files(path = dir_data, pattern = 'city_total_draws_by_cause.csv', full.names = T, recursive = T)
fs

df_all <- map_dfr(fs, ~ read_csv(.x, show_col_types = FALSE) %>%
  # mutate(Scenario = str_extract(.x, "s\\d+_s\\d+(?=_|/|$)")))  # without '_2050_2050'
  mutate(Scenario = str_extract(.x, "s\\d+_s\\d+(?:_\\d+_\\d+)?")))
  # mutate(Scenario = str_extract(.x, "s\\d+_s\\d+(?=/|$)")))
causes <- setdiff(names(df_all), c("draw", "Scenario"))
causes

```



```{r - re-code data }

df_all_ <- df_all %>%
  mutate(
    year = str_extract(Scenario, "\\d{4}_\\d{4}"),
    year = ifelse(is.na(year), '2021_2050', year), 
    Scenario = str_remove(Scenario, "_\\d{4}_\\d{4}")
) %>%
  tidyr::separate(year, into = c("yr_ini", "yr_end"), sep = "_", remove = FALSE) %>%
  mutate(
    label = case_when(
      (yr_ini == yr_end) & !is.na(yr_end) ~ 'lc effect',
      TRUE ~ 'climate+lc effect'
    ) 
  ) %>%
  ## re-code: change scenario-3 (tree risk) as scenario-2
  mutate(
    lc_scenario = gsub('s0_', '', Scenario),
    lc_scenario = case_when(
      lc_scenario == 's1'  ~ 'scenario1',
      lc_scenario == 's2'  ~ 'scenario3_TO',
      lc_scenario == 's3'  ~ 'scenario2_TR',
      lc_scenario == 's41' ~ 'scenario4_10',
      lc_scenario == 's42' ~ 'scenario4_20',
      lc_scenario == 's43' ~ 'scenario4_30',
      TRUE                 ~ NA_character_
    ) 
  ) %>%
  as.data.frame()
```



```{r - which data?}

what_effect <- 'climate+lc effect'; year_range <- '2021_2050' ## yr_0 & lc_0
what_effect <- 'lc effect';         year_range <- '2050_2050' ## yr_i & lc_0
# what_effect <- 'lc effect';         year_range <- '2070_2070' ## yr_i & lc_0 # --> the result is the same as '2050_2070'

df_all_filter <- df_all_ %>%
  filter(label == what_effect) %>%
  filter(year %in% year_range)
```




```{r - data 1}

long <- df_all_filter %>%
  # select(-draw) %>%
  pivot_longer(all_of(causes), names_to = "cause", values_to = "value") %>%
  drop_na() %>%
  mutate(cause = factor(cause, levels = causes))

stats <- long %>%
  group_by(cause, lc_scenario) %>%
  summarise(
    mean  = mean(value, na.rm = TRUE),
    median= median(value, na.rm = TRUE),
    p25   = quantile(value, 0.25, na.rm = TRUE),
    p75   = quantile(value, 0.75, na.rm = TRUE),
    p2    = quantile(value, 0.025, na.rm = TRUE),
    p97   = quantile(value, 0.975, na.rm = TRUE),
    .groups = "drop"
  )



# --- plot ---
p <- ggplot(long, aes(x = value, y = cause)) +
  # geom_violin(aes(group = cause), draw_quantiles = 0.5, 
  #             fill = 'lightblue', color = NA,
  #             linewidth = 0, alpha=0.9, trim = FALSE) +
  
  geom_violin(aes(group = interaction(cause, lc_scenario)), fill="lightblue",
              color = NA, linewidth = 0, alpha = 0.9, trim = FALSE) +
  facet_wrap(~ lc_scenario) +
  
  
  # 95% interval (thin bar)
  geom_segment(data = stats, aes(x = p2, xend = p97, y = cause, yend = cause), linewidth = 0.6, alpha = 0.6) +
  # IQR (thick bar)
  # geom_segment(data = stats, aes(x = p25, xend = p75, y = cause, yend = cause), linewidth = 2, alpha = 0.6) +
  geom_point(data = stats, aes(x = mean, y = cause),
             shape = 18, size = 2.5, color = "red", alpha = 0.4) +
  geom_text(data = stats, aes(x = mean, y = cause, label = sprintf("%.0f", mean)),
            vjust = -0.5, size = 3, color = "red") +
  labs(x = "Excess deaths (city total)", y = NULL,
       title = "Monte Carlo distributions by cause") +
  theme_bw(base_size = 11)
p
# --- save ---
# dir.create(dir_fig, showWarnings = FALSE, recursive = TRUE)
# ggsave(file.path(dir_fig, "health_monte_carlo_violins_by_cause.png"),
#        p, width = 6, height = 4, dpi = 300)



```


```{r - data 2}

long2 <- 
  df_all_ %>%
  pivot_longer(all_of(causes), names_to = "cause", values_to = "value") %>%
  # drop_na(value) %>%
  # mutate(
  #   year = str_extract(Scenario, "\\d{4}_\\d{4}"),
  #   Scenario = str_remove(Scenario, "_\\d{4}_\\d{4}"), 
  #   year = ifelse(is.na(year), '2021_2050', year)
  #   ) %>%
  mutate(cause = str_to_title(cause))

# keep original cause order as in the first file
first_cols <- names(read_csv(fs[1], n_max = 0, show_col_types = FALSE)) %>%
  str_to_title()

cause_order <- setdiff(first_cols, "Draw")

long2 <- long2 |>
  mutate(
    cause = factor(cause, levels = cause_order),
    lc_scenario   = factor(lc_scenario)
  ) %>%
  filter(year %in% year_range)

#-----------------------------
# 2) Summary stats per cause × lc_scenario
#-----------------------------
stats <- long2 |>
  group_by(cause, lc_scenario, label, yr_end) |>
  summarise(
    mean  = mean(value, na.rm = TRUE),
    median= median(value, na.rm = TRUE),
    # 25th percentile (lower quartile, Q1) → lower bound of the IQR
    p25   = quantile(value, 0.25, na.rm = TRUE),
    # 75th percentile (upper quartile, Q3) → upper bound of the IQR
    p75   = quantile(value, 0.75, na.rm = TRUE),
    # 2.5th percentile → lower bound of ~95% central interval
    p2    = quantile(value, 0.025, na.rm = TRUE),
    # 97.5th percentile → upper bound of ~95% central interval
    p97   = quantile(value, 0.975, na.rm = TRUE),
    
    sd = sd(value, na.rm = TRUE),                 # standard deviation
    n  = dplyr::n(),                                   # sample size
    se = sd / sqrt(n),                                 # standard error
    ci_lower = mean - 1.96 * se,
    ci_upper = mean + 1.96 * se, 
    .groups = "drop"
  )
```




```{r - plot}

#-----------------------------
# 3) Plot (vertical, dodged by lc_scenario)
#-----------------------------

source(here('code', 'func_colors.R')) # `scenario_colors`


pd <- position_dodge2(width = 0.7, preserve = "single")
# pd <- position_dodge(width = 0.7)

mean_min <- min(stats$mean, na.rm = T); mean_min
legend.position.x <- ifelse(mean_min>=0, .85, 0.15)

## data for plot
stats_p <- stats %>%
  mutate(
    cause = factor(cause, levels = unique(cause)),   # discrete x
    mean_text = ifelse(abs(mean) < 2, NA, round(mean, digits = 0))       # do not show small numbers
  ) 


## decide if to use geom_segment

if (what_effect == 'climate+lc effect') {
  
  ## --- 1 --- plot change attributable to the combination of climate and LC ---
  hjust_label <- 0.5
  vjust_label <- 2.0
  legend_y    <- 0.8
  
  p <- stats_p %>%
    ggplot(data = ., 
           aes(x = cause, y = mean, 
               group = lc_scenario, 
               color = lc_scenario)) +
    geom_point(
      position = pd, shape = 1, size = 2, stroke = 1, alpha = 0.8) +
    labs(x = NULL, y = "Excess deaths (city total)")
  
  
  ## --- 2 --- plot change attributable to LC ONLY -----------------------------
} else {
  hjust_label <- 1.5 
  vjust_label <- 0
  legend_y    <- 0.2
  
  p <- stats_p %>%
    select(1:mean, ci_lower, ci_upper, mean_text) %>%
    ## convert "Excess deaths" to "Preventable deaths" to indicate "benefits" of nature
    pivot_longer(names_to = 'col', values_to = 'value', cols = mean:mean_text) %>%
    mutate(value = -value) %>%
    pivot_wider(names_from = 'col', values_from = 'value') %>%
    
    ggplot(data = ., 
           aes(x = cause, y = mean, 
               group = lc_scenario, 
               color = lc_scenario)) +
    
    # vertical reference segments (0 -> mean), dodged the same as points
    geom_segment(aes(x = cause, y = 0, yend = mean, group = lc_scenario),
                 position = pd, 
                 show.legend = FALSE,
                 # color = "grey90", 
                 alpha = 0.6, 
                 na.rm = TRUE,
                 linewidth = 0.5) +
    geom_point(
      position = pd, shape = 1, size = 2, stroke = 1, alpha = 0.8) +
    geom_hline(yintercept = 0, linetype = 'dashed', colour = 'gray', show.legend = FALSE) +
    labs(x = NULL, y = "Preventable deaths (city total)")
}


## --- 3 --- overall setting 
p <- p +
  
  # geom_errorbar(
  #   aes(ymin = mean-sd, ymax = mean+sd),
  #   width = 0.12, alpha = 0.6,
  #   position = pd, show.legend = F,
  # ) +
  # mean labels (aligned with dodged violins)
  geom_text(
    aes(label = mean_text),
    position = pd, 
    hjust = hjust_label, 
    vjust = vjust_label,
    size = 2, show.legend = FALSE
  ) +
  
  scale_color_manual(
    # # remove the "scenario0" color from the named vector
    values = scenario_colors[names(scenario_colors) != "scenario0"] ) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.05))) +
  
  # coord_flip() +
  # give a bit of right margin so nudged labels don’t clip
  coord_cartesian(clip = "off") +
  theme(
    # legend.position = c(legend.position.x, .75), # when using `coord_flip`
    legend.position = c(0.9, legend_y),
    legend.spacing.y  = unit(0.05, "cm"),
    legend.key.size = unit(1, "pt"),
    legend.background = element_rect(fill = "transparent", color = NA),
    legend.key = element_rect(fill = "transparent", color = NA),
    # panel.grid.major.y = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    # legend.title = element_blank(),
    # axis.text.x = element_text(angle = 45, hjust = 1)
  )
p


#-----------------------------
# 4) Save
#-----------------------------
dir.create(dir_fig, showWarnings = FALSE, recursive = TRUE)
f <- file.path(dir_fig, paste0("health_monte_carlo_violins_by_cause_Scenario_dodged_", year_range, '_', ymd, ".png")); f
ggsave(filename = f, plot = p, width = 7, height = 3, dpi = 300)

```

