---
title: "Untitled"
output: html_document
date: "2025-11-10"
---


## Setup 

  This script aims to process the *NEWLY* calculated work productivity data aside from the UCM. 
  
  The output figures were generated using the same function from those for plotting average change in temp, and energy


```{r}

# # To clear your environment 
# remove(list = ls())

library(here)
source(here::here('code', 'func_packages.R'))


here()
source(here('code', 'func_ggsave.R'))
source(here('code', 'func_get_color_scale.R'))
source(here('code', 'func_colors.R')) # scenario_colors

theme_set(theme_bw(base_size = 11))

dir.g <- "G:/Shared drives/Wellcome Trust Project Data"
dir.aoi      <- file.path(dir.g, "1_preprocess/UrbanCoolingModel/OfficialWorkingInputs/AOIs")
dir_ucm_out  <- file.path(dir.g, '2_postprocess_intermediate/UCM_official_runs')
dir_prod_new <- file.path(dir_ucm_out, 'new_work_intensity')
dir.fig <- file.path(dir.g, "3_final/UCM_figures")


# load functions 
f <- here("code", "func_calculate_change_from_yri_lc0.rds");
func_calculate_change_from_yri_lc0 <- readRDS(f)

f <- here('code', 'func_calculate_change_from_yr0_lc0.rds');
func_calculate_change_from_yr0_lc0 <- readRDS(f)

f <- here('code', 'func_combine_two_change_dfs.rds')
func_combine_two_change_dfs <- readRDS(f) 

f <- here('code', 'func_plot_line.rds')
func_plot_line <- readRDS(f)

f <- here('code', 'func_plot_change_point.rds')
func_plot_change_point <- readRDS(f)

f <- here('code', 'func_plot_map.rds')
func_plot_map <- readRDS(f)
```


## Data


### AOI

```{r}

#' borough level
f <- file.path(dir.aoi, 'London_Borough_aoi.shp')
aoi <- st_read(f, quiet = T) %>% select(GSS_CODE)


#' lsoa data with quintiles info, which was generated by `socio-economic-data-ES-equity.Rmd`
f <- './data/Social_Vulnerability_Index_london_q.gpkg'
aoi_lsoa <- st_read(f, quiet = T) %>%
  rename('GSS_CODE' = 'id') %>%
  mutate(GSS_CODE = as.character(GSS_CODE)) %>%
  select(GSS_CODE)

```



### ? Pick one scale ---

  Data csv from zonal stats
  
### Load data - borough level 

```{r}

sp_scale = "borough"

f <- file.path(dir_prod_new, 'zonal_stats_borough', 'work_productivity_42_zonal_stats_long.csv'); f
d <- read_csv(f, show_col_types = F) 


pd <- d %>%
  mutate(
    year = case_when(
      str_detect(scenario, "20_2") ~ '2020',
      str_detect(scenario, "22_2") ~ '2021',
      str_detect(scenario, "22_5") ~ '2030',
      str_detect(scenario, "25_5") ~ '2050',
      str_detect(scenario, "28_5") ~ '2070',
      TRUE ~ NA_character_
    )
  ) %>%
  
  # rename the variable as `hvpd` - Heavy work productivity (%)
  rename('avg_hvpd_v' = 'mean') %>%
  # scale 0-1 to 0-100 (i.e., %)
  mutate(avg_hvpd_v = round(as.numeric(avg_hvpd_v)*100, digits = 2)) %>%
  select(-any_of(c('raster', 'source'))) %>%
  
  ## re-code: change scenario-3 (tree risk) as scenario-2
  mutate(
    lc_scenario = case_when(
      lc_scenario == 'scenario3'   ~ 'scenario2_TR',
      lc_scenario == 'scenario2'   ~ 'scenario3_TO',
      lc_scenario == 'scenario41'  ~ 'scenario4_10',
      lc_scenario == 'scenario42'  ~ 'scenario4_20',
      lc_scenario == 'scenario43'  ~ 'scenario4_30',
      TRUE                        ~ lc_scenario
    ) 
  ) %>%
  as.data.frame()

unique(pd$lc_scenario)
```


   - reload saved data -> filter
   
```{r}

pd_sf <- pd %>%
  left_join(., aoi, by = c("GSS_CODE"))


## pick the baseline year for later comparison 
year_baseline <- 2021


## filter out 20_5, and 22_5, 25_2 for now 
pd_sf_filter <- pd_sf %>%
  filter(!is.na(year))

```





```{r - data stats}

ind <- 'avg_hvpd_v'
ind_scale <- 1  ## Here we use value 1 because the new outcome is "work productivity" (0-1), while the UCM produces "productivity loss" (then the scale factor will use -1). 
ind_label <- "heavy work productivity (%)"


# 1. calculate the change from year i
df_stats_i0 <- func_calculate_change_from_yri_lc0(data = pd_sf_filter, aoi = aoi)
df_chg_sf_i0<- func_calculate_change_from_yri_lc0(data = pd_sf_filter, aoi = aoi, return_sf = T)


# 2. also calculate the change from year 0
df_stats_00 <- func_calculate_change_from_yr0_lc0(data = pd_sf_filter, aoi = aoi)

# 3. and combine the two change calculations  
#    --> see ### `Re-code Land scenario`

```



### Load data - lsoa level 
  
```{r - data stats, eval=FALSE, include=FALSE}

sp_scale = "lsoa"

ind <- 'avg_hvpd_v'
ind_scale <- 1
ind_label <- "heavy work productivity (%)"



f <- paste0('./data/', 'ucm_output_shp_stats_productivity_by_lsoa.rds'); f
shp_all_df <- readRDS(f) %>%
  mutate(GSS_CODE = as.character(GSS_CODE)) %>%
  rename(ind = 'mean') #%>%
  ## add sf info, as this data does not have spatail info
  # left_join(aoi_lsoa, ., by = 'GSS_CODE')

# 1. calculate the change from year i
df_stats_i0 <- func_calculate_change_from_yri_lc0(data = shp_all_df, aoi = aoi_lsoa)
df_chg_sf_i0<- func_calculate_change_from_yri_lc0(data = shp_all_df, aoi = aoi_lsoa, return_sf = T)


# 2. also calculate the change from year 0
df_stats_00 <- func_calculate_change_from_yr0_lc0(data = shp_all_df)


# 3. and combine the two change calculations  
#    --> see ### `Re-code Land scenario`

```
  
### Re-code Land scenario

```{r}
## re-code land scenario labels
df_stats_00 <- df_stats_00 %>%
  mutate(lc_scenario = factor(lc_scenario, 
                              levels = names(scenario_labels),
                              labels = unname(scenario_labels)))

df_stats_i0 <- df_stats_i0 %>%
  mutate(lc_scenario = factor(lc_scenario, 
                              levels = names(scenario_labels),
                              labels = unname(scenario_labels)))

# 3. and combine the two change calculations  
stat_both_l <- func_combine_two_change_dfs(df_stats_00, df_stats_i0)
```


### Plot 

```{r - plot - line}

## plot change from year i, old plot 
df_stats_input <- df_stats_i0 %>% 
  filter(year >= year_baseline) %>%
  mutate(year = as.factor(year)) %>%
  as.data.frame()
func_plot_line(data = df_stats_input)

## plot change from year i 
func_plot_change_point(data = stat_both_l, level = sp_scale, plot_avg = F)
func_plot_change_point(data = stat_both_l, level = sp_scale, plot_h = 4, plot_avg = T)

```


```{r - plot - map}

df_change_sf_input <- df_chg_sf_i0 %>% 
  filter(year > year_baseline) %>%
  mutate(year = as.factor(year)) %>%
  mutate(lc_scenario = factor(lc_scenario, 
                              levels = names(scenario_labels),
                              labels = unname(scenario_labels)))

## save a copy for viz
f <- paste0('./data/', 'viz_sf_', ind, '_lc_effect_', sp_scale, '.rds'); f
# "./data/viz_sf_avg_hvpd_v_lc_effect.rds"
saveRDS(df_change_sf_input, f)


## apply the function 
func_plot_map(data = df_change_sf_input, level = sp_scale)

```





