---
title: "Untitled"
output: html_document
date: "2025-09-16"
---


## Setup 

```{r}
knitr::opts_chunk$set(warning = FALSE)

# To clear your environment 
remove(list = ls())

# load common packages
library(here)
here()
source(here('code', 'func_packages.R'))
source(here('code', 'func_ggsave.R'))
source(here('code', 'func_get_color_scale.R'))

dir.fig <- "G:/Shared drives/Wellcome Trust Project Data/3_final/UCM_figures"
dir_ucm_out <- 'G:/Shared drives/Wellcome Trust Project Data/2_postprocess_intermediate/UCM_official_runs'

theme_set(theme_bw(base_size = 11))
```


## Borough-levle Data

### CVS data from zonal stats

```{r}


f <- file.path(dir_ucm_out, 'ucm_output_postprocess', 'T_air_london_22_zonal_stats_long.csv'); f

d <- read_csv(f, show_col_types = F) 


df <- d %>%
  mutate(
    year = case_when(
      str_detect(raster, "20.0deg_2.0uhi") ~ '2020',
      str_detect(raster, "22.0deg_2.0uhi") ~ '2021',
      str_detect(raster, "22deg_2uhi")     ~ '2021',
      # str_detect(raster, "22deg_5uhi")     ~ '2030',
      str_detect(raster, "25.0deg_5.0uhi") ~ '2050',
      str_detect(raster, "25deg_5uhi")     ~ '2050',
      str_detect(raster, "28deg_5uhi")     ~ '2070',
      TRUE ~ NA_character_
    )
  ) %>%
  rename('T_mean' = 'mean') %>%
  select(-any_of(c('raster', 'source'))) %>%
  mutate(T_mean = round(as.numeric(T_mean), digits = 3))
```



```{r - plot}

# Example summarisation (if df has replicates per group)
df_summary <- df %>%
  as.data.frame() %>%
  group_by(lc_scenario, year) %>%
  # dplyr::group_by(lc_scenario, climate) %>%
  dplyr::summarise(
    mean = mean(T_mean, na.rm = TRUE),          # group mean
    sd   = sd(T_mean, na.rm = TRUE),            # standard deviation
    n    = n(),                               # sample size
    se   = sd / sqrt(n)                       # standard error
  )


# Bar plot with error bars

df_summary %>%
  ggplot(., aes(x = lc_scenario, y = mean)) +
  geom_col(position = position_dodge(width = 0.9), alpha = 0.5) +
  geom_errorbar(
    aes(ymin = mean - sd, ymax = mean + sd),
    width = 0.2, alpha = 0.5, 
    position = position_dodge(width = 0.9)
  ) +
  
  # add mean values as text labels
  geom_text(
    aes(label = round(mean, 1), y = mean),   # label from mean
    vjust = -0.5,                            # push above bar
    size = 4, color = 'red'                  # adjust font size
  ) +
  
  # facet_wrap(~ year) + # , scale = 'free_y'
  facet_wrap(~ year, scale = 'free') + # 
  labs(
    x = "Land Cover Scenario",
    y = "Mean Value ± SD",
    # fill = "year"
  ) +
  # scale_fill_brewer(palette = "Set2", direction = 1) +  # reverse order
  theme_bw() +
  coord_cartesian(ylim = c(20, NA)) +   # start at 20, let top auto-scale
  scale_y_continuous(expand = c(0, 1)) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )


# Save your last ggplot as PNG
f <- file.path(dir.fig, paste0("temp_scenarios_fromRaster_", ymd, ".png"))
ggsave(
  filename = f, 
  width    = 7,                    # width in inches
  height   = 8,                    # height in inches
  units = 'in',
  dpi      = 300                   # resolution (good for PPT/publications)
)


```


### Shp data from UCM output


```{r - function}

library(stringr)
library(sf)
library(purrr)
library(dplyr)

# --- helper function for clean IDs ---

extract_id <- function(path) {
  # 1) get just filename (no folder, no extension)
  fname <- tools::file_path_sans_ext(basename(path))
  
  # 2) replace pieces according to your example
  #    "uhi_results_london_scenario_20.0deg_2.0uhi_66.9hum_energy_productivity"
  # →  "uhi_results_20_2"
  fname <- str_replace(fname, "uhi_results_london_scenario_", "uhi_results_")
  
  # 3) clean decimals
  fname <- str_replace(fname, "(\\d+)\\.0deg", "\\1")   # 20.0deg → 20
  fname <- str_replace(fname, "(\\d+)\\.0uhi", "\\1")   # 2.0uhi  → 2
  
  # 4) remove trailing pieces (hum, energy_productivity, etc.)
  fname <- str_replace(fname, "_\\d+\\.?\\d*hum.*", "")
  
  # 5) prefix with subfolder part (e.g. current_lulc)
  folder <- basename(dirname(dirname(path)))  # two folders up
  paste0(folder, "_", fname)
}

```



```{r - batch load - taking long time ..., message=FALSE}

shp_files <- list.files(
  path = dir_ucm_out, 
  pattern = "^uhi_results.*energy_productivity.shp$", 
  full.names = TRUE, recursive = T
)

(shp_files)

cat('There are', length(shp_files), 'files.')

# # read all into a list of sf objects
# shp_list <- map(shp_files, st_read)
# 
# # optionally name the list by file
# names(shp_list) <- basename(shp_files)




# --- read and combine ---
#' map2_dfr() loops over (file, id) pairs.
#' map2_dfr(..., .id = NULL) row-binds everything into one big sf object.
shp_all <- map2_dfr(
  shp_files,
  map_chr(shp_files, extract_id),
  ~ st_read(.x, quiet = T) %>% mutate(id = .y),
  .id = NULL
)

# result: one sf object

f <- file.path(dir_ucm_out, 'ucm_output_postprocess', 'uhi_results_combined_sf.rds')
saveRDS(object = shp_all, file = f)
```



```{r - save aoi in sf}

f <- file.path(dir_ucm_out, 'ucm_output_postprocess', 'uhi_results_combined_sf.rds')
shp_all <- readRDS(f)

aoi <- shp_all %>%
  group_by(NAME, GSS_CODE) %>%
  slice(1) %>%
  select(NAME, GSS_CODE) %>%
  ungroup()


f <- file.path(dir_ucm_out, 'ucm_output_postprocess', 'aoi_sf.rds')
saveRDS(object = aoi, file = f)
```



### Reload data

```{r - reload saved data}

f <- file.path(dir_ucm_out, 'ucm_output_postprocess', 'uhi_results_combined_sf.rds')
shp_all <- readRDS(f)


f <- file.path(dir_ucm_out, 'ucm_output_postprocess', 'aoi_sf.rds')
aoi <- readRDS(f)

```


```{r - re-code df}

## pick the baseline year for later comparison 
year_baseline <- 2021


## tidy and re-code data 
shp_all_ <- shp_all %>%
  st_drop_geometry() %>%
  select(-any_of(c("HECTARES", 
                   "NONLD_AREA", "ONS_INNER",  "SUB_2009", "SUB_2006"))) %>%
  mutate(
    id = gsub('work_and_energy_runs_uhi_results_london_', '', id),
    
    # re-code: climate condition --> year
    year = case_when(
      str_detect(id, "_20_2")            ~ '2020',
      # str_detect(id, "_20_5") ~ '20_5',
      
      str_detect(id, "_22_2|22deg_2uhi") ~ '2021',
      str_detect(id, "_22_5|22deg_5uhi") ~ '2030',
      
      # str_detect(id, "_25_2|25deg_2uhi") ~ '25_2',
      str_detect(id, "_25_5|25deg_5uhi") ~ '2050', # 2050
      
      # str_detect(id, "_28_2|28deg_2uhi") ~ '28_2', 
      str_detect(id, "_28_5|28deg_5uhi") ~ '2070', 
      TRUE ~ NA_character_
    ) 
  ) %>%

  tidyr::separate(id, into = c("lc_scenario", "rest"), sep = "_uhi_results|prc", remove = FALSE) %>%
  select(-rest) %>%
  mutate(lc_scenario = gsub('_20_2|_22_2|_25_5', '', lc_scenario) ) %>%
  
  ## re-code: change scenario-3 (tree risk) as scenario-2
  mutate(

    lc_scenario = case_when(
      lc_scenario == 'scenario3'  ~ 'scenario2_TR',
      lc_scenario == 'scenario2'  ~ 'scenario3_TO',
      TRUE                        ~ lc_scenario
    ) 
  ) %>%
  as.data.frame()



## filter out 20_5, and 22_5, 25_2 for now 

shp_all_df <- shp_all_ %>%
  filter(!is.na(year))


## save a copy for viz
f <- paste0('./data/', 'ucm_output_shp_stats_outcomes_by_borough.rds'); f
saveRDS(shp_all_df, f)

```



## LSOA level stats

### Energy 

```{r - batch load}

dir.zonal <- file.path(dir_ucm_out, 'zonal_stats_lsoa')

# batch load data
library(purrr)

shp_files <- list.files(path = dir.zonal, pattern = ".*_energy_stats.gpkg$", full.names = TRUE, recursive = F)
cat('There are', length(shp_files), 'files.')

# --- helper function for clean IDs ---
extract_id <- function(path) {
  # 1) get just filename (no folder, no extension)
  fname <- tools::file_path_sans_ext(basename(path))
  
  # 2) replace pieces according to your example
  fname <- str_replace(fname, "work_and_energy_runs_", "")
  
  # 3) clean decimals
  fname <- str_replace(fname, "(\\d+)\\.0deg", "\\1")   # 20.0deg → 20
  fname <- str_replace(fname, "(\\d+)\\.0uhi", "\\1")   # 2.0uhi  → 2
  
  # 4) remove trailing pieces (hum, energy_productivity, etc.)
  fname <- str_replace(fname, "_\\d+\\.?\\d*hum.*", "")
  
  return(fname)
}

# --- read and combine ---
shp_all <- map2_dfr(
  shp_files,
  map_chr(shp_files, extract_id),
  ~ st_read(.x, quiet = T) %>% mutate(id = .y),
  .id = NULL
)

# # result: one sf object
# 
# f <- file.path(dir_ucm_out, 'ucm_output_postprocess', 'uhi_results_combined_sf.rds')
# saveRDS(object = shp_all, file = f)
```
  
  
  
```{r - re-code}

## pick the baseline year for later comparison 
year_baseline <- 2021


## tidy and re-code data 
shp_all_ <- shp_all %>%
  st_drop_geometry() %>%
  select(-any_of(c("Neighborhood_name", "metric_category"))) %>%
  mutate(

    # re-code: climate condition --> year
    year = case_when(
      str_detect(id, "_20_2")            ~ '2020',
      str_detect(id, "_22_2|22deg_2uhi") ~ '2021',
      str_detect(id, "_22_5|22deg_5uhi") ~ '2030',
      str_detect(id, "_25_5|25deg_5uhi") ~ '2050',
      str_detect(id, "_28_5|28deg_5uhi") ~ '2070', 
      TRUE ~ NA_character_
    ) 
  ) %>%

  ## re-code: change scenario-3 (tree risk) as scenario-2
  rename('lc_scenario' = 'scenario') %>%
  mutate(
    lc_scenario = case_when(
      lc_scenario == 'scenario3'  ~ 'scenario2_TR',
      lc_scenario == 'scenario2'  ~ 'scenario3_TO',
      TRUE                        ~ lc_scenario
    ) 
  ) %>%
  as.data.frame()


## filter out 20_5, and 22_5, 25_2 for now 
shp_all_lsoa <- shp_all_ %>%
  filter(!is.na(year))


## save a copy for viz
f <- paste0('./data/', 'ucm_output_shp_stats_energy_by_lsoa.rds'); f
saveRDS(shp_all_lsoa, f)

```
