---
title: "Untitled"
output: html_document
date: "2025-09-16"
---

```{r setup}

# To clear your environment 
remove(list = ls())

library(here)
library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)

theme_set(theme_bw(base_size = 16))

ymd   <- format(Sys.time(), "%Y%m%d"); ymd

here()
source(here('code', 'func_ggsave.R'))
source(here('code', 'func_get_color_scale.R'))

dir.fig <- "G:/Shared drives/Wellcome Trust Project Data/3_final/UCM_figures"


dir_ucm_out <- 'G:/Shared drives/Wellcome Trust Project Data/2_postprocess_intermediate/UCM_official_runs'
```


## Data

### CVS data from zonal stats

```{r}


f <- file.path(dir_ucm_out, 'ucm_output_postprocess', 'T_air_london_22_zonal_stats_long.csv'); f

d <- read_csv(f, show_col_types = F) 


df <- d %>%
  mutate(
    year = case_when(
      str_detect(raster, "20.0deg_2.0uhi") ~ '2020',
      str_detect(raster, "22.0deg_2.0uhi") ~ '2021',
      str_detect(raster, "22deg_2uhi")     ~ '2021',
      str_detect(raster, "25.0deg_5.0uhi") ~ '2050',
      str_detect(raster, "25deg_5uhi")     ~ '2050',
      str_detect(raster, "28deg_5uhi")     ~ '2070',
      TRUE ~ NA_character_
    )
  ) %>%
  
  # mutate(climate = str_extract(raster, "\\d+deg_\\d+uhi")) %>%
  # mutate(
  #    climate = case_when(
  #      year < 2030 ~ 'current',
  #      T ~ 'future'
  #    )
  #    ) %>%
  rename('T_mean' = 'mean') %>%
  select(-any_of(c('raster', 'source'))) %>%
  mutate(T_mean = round(as.numeric(T_mean), digits = 3))
```



```{r - plot}

# Example summarisation (if df has replicates per group)
df_summary <- df %>%
  as.data.frame() %>%
  group_by(lc_scenario, year) %>%
  # dplyr::group_by(lc_scenario, climate) %>%
  dplyr::summarise(
    mean = mean(T_mean, na.rm = TRUE),          # group mean
    sd   = sd(T_mean, na.rm = TRUE),            # standard deviation
    n    = n(),                               # sample size
    se   = sd / sqrt(n)                       # standard error
  )


# Bar plot with error bars

df_summary %>%
  ggplot(., aes(x = lc_scenario, y = mean)) +
  geom_col(position = position_dodge(width = 0.9), alpha = 0.5) +
  geom_errorbar(
    aes(ymin = mean - sd, ymax = mean + sd),
    width = 0.2, alpha = 0.5, 
    position = position_dodge(width = 0.9)
  ) +
  
  # add mean values as text labels
  geom_text(
    aes(label = round(mean, 1), y = mean),   # label from mean
    vjust = -0.5,                            # push above bar
    size = 4, color = 'red'                  # adjust font size
  ) +
  
  # facet_wrap(~ year) + # , scale = 'free_y'
  facet_wrap(~ year, scale = 'free') + # 
  labs(
    x = "Land Cover Scenario",
    y = "Mean Value ± SD",
    # fill = "year"
  ) +
  # scale_fill_brewer(palette = "Set2", direction = 1) +  # reverse order
  theme_bw() +
  coord_cartesian(ylim = c(20, NA)) +   # start at 20, let top auto-scale
  scale_y_continuous(expand = c(0, 1)) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )


# Save your last ggplot as PNG
f <- file.path(dir.fig, paste0("temp_scenarios_fromRaster_", ymd, ".png"))
ggsave(
  filename = f, 
  width    = 7,                    # width in inches
  height   = 8,                    # height in inches
  units = 'in',
  dpi      = 300                   # resolution (good for PPT/publications)
)


```


### Shp data from UCM output


```{r - function}

library(stringr)
library(sf)
library(purrr)
library(dplyr)

# --- helper function for clean IDs ---

extract_id <- function(path) {
  # 1) get just filename (no folder, no extension)
  fname <- tools::file_path_sans_ext(basename(path))
  
  # 2) replace pieces according to your example
  #    "uhi_results_london_scenario_20.0deg_2.0uhi_66.9hum_energy_productivity"
  # →  "uhi_results_20_2"
  fname <- str_replace(fname, "uhi_results_london_scenario_", "uhi_results_")
  
  # 3) clean decimals
  fname <- str_replace(fname, "(\\d+)\\.0deg", "\\1")   # 20.0deg → 20
  fname <- str_replace(fname, "(\\d+)\\.0uhi", "\\1")   # 2.0uhi  → 2
  
  # 4) remove trailing pieces (hum, energy_productivity, etc.)
  fname <- str_replace(fname, "_\\d+\\.?\\d*hum.*", "")
  
  # 5) prefix with subfolder part (e.g. current_lulc)
  folder <- basename(dirname(dirname(path)))  # two folders up
  paste0(folder, "_", fname)
}

```



```{r - batch load, message=FALSE}

shp_files <- list.files(
  path = dir_ucm_out, 
  pattern = "^uhi_results.*energy_productivity.shp$", 
  full.names = TRUE, recursive = T
)

(shp_files)

cat('There are', length(shp_files), 'files.')

# # read all into a list of sf objects
# shp_list <- map(shp_files, st_read)
# 
# # optionally name the list by file
# names(shp_list) <- basename(shp_files)




# --- read and combine ---
#' map2_dfr() loops over (file, id) pairs.
#' map2_dfr(..., .id = NULL) row-binds everything into one big sf object.
shp_all <- map2_dfr(
  shp_files,
  map_chr(shp_files, extract_id),
  ~ st_read(.x, quiet = T) %>% mutate(id = .y),
  .id = NULL
)

# result: one sf object

f <- file.path(dir_ucm_out, 'ucm_output_postprocess', 'uhi_results_combined_sf.rds')
saveRDS(object = shp_all, file = f)
```



```{r - save aoi in sf}

f <- file.path(dir_ucm_out, 'ucm_output_postprocess', 'uhi_results_combined_sf.rds')
shp_all <- readRDS(f)

aoi <- shp_all %>%
  group_by(NAME, GSS_CODE) %>%
  slice(1) %>%
  select(NAME, GSS_CODE) %>%
  ungroup()


f <- file.path(dir_ucm_out, 'ucm_output_postprocess', 'aoi_sf.rds')
saveRDS(object = aoi, file = f)
```



### Reload data

```{r - reload saved data}

f <- file.path(dir_ucm_out, 'ucm_output_postprocess', 'uhi_results_combined_sf.rds')
shp_all <- readRDS(f)


f <- file.path(dir_ucm_out, 'ucm_output_postprocess', 'aoi_sf.rds')
aoi <- readRDS(f)

```


```{r - re-code df}

## pick the baseline year for later comparison 
year_baseline <- 2021


## tidy and re-code data 
shp_all_ <- shp_all %>%
  st_drop_geometry() %>%
  select(-any_of(c("HECTARES", 
                   "NONLD_AREA", "ONS_INNER",  "SUB_2009", "SUB_2006"))) %>%
  mutate(
    id = gsub('work_and_energy_runs_uhi_results_london_', '', id),
    
    # re-code: climate condition --> year
    year = case_when(
      str_detect(id, "_20_2")            ~ '2020',
      # str_detect(id, "_20_5") ~ '20_5',
      
      str_detect(id, "_22_2|22deg_2uhi") ~ '2021',
      str_detect(id, "_22_5|22deg_5uhi") ~ '2030',
      
      # str_detect(id, "_25_2|25deg_2uhi") ~ '25_2',
      str_detect(id, "_25_5|25deg_5uhi") ~ '2050', # 2050
      
      # str_detect(id, "_28_2|28deg_2uhi") ~ '28_2', 
      str_detect(id, "_28_5|28deg_5uhi") ~ '2070', 
      TRUE ~ NA_character_
    ) 
  ) %>%

  tidyr::separate(id, into = c("lc_scenario", "rest"), sep = "_uhi_results|prc", remove = FALSE) %>%
  select(-rest) %>%
  mutate(lc_scenario = gsub('_20_2|_22_2|_25_5', '', lc_scenario) ) %>%
  
  ## re-code: change scenario-3 (tree risk) as scenario-2
  mutate(

    lc_scenario = case_when(
      lc_scenario == 'scenario3'  ~ 'scenario2_TR',
      lc_scenario == 'scenario2'  ~ 'scenario3_TO',
      TRUE                        ~ lc_scenario
    ) 
  ) %>%
  as.data.frame()



## filter out 20_5, and 22_5, 25_2 for now 

shp_all_df <- shp_all_ %>%
  filter(!is.na(year))

```




```{r - colors}

source(here('code', 'func_colors.R')) # scenario_colors

```




```{r - summary df}

# Example summarisation (if df has replicates per group)
# names(shp_all_df)

df_summary_fromshp <- shp_all_df %>%
  rename('T_mean' = 'avg_tmp_v') %>%
  as.data.frame() %>%
  group_by(lc_scenario, year) %>%
  dplyr::summarise(
    mean = mean(T_mean, na.rm = TRUE),          # group mean
    sd   = sd(T_mean, na.rm = TRUE),            # standard deviation
    n    = n(),                               # sample size
    se   = sd / sqrt(n)                       # standard error
  ) %>%
  # ungroup() %>%
  as.data.frame()


unique(df_summary_fromshp$lc_scenario)
```


### Average temperature

  `avg_tmp_v` - Average temperature value (degC).

```{r - stats: change from yr i + lc 0}

ind <- 'avg_tmp_v'
ind_scale <- 1
ind_label <- "temperature (°C)"


## compare to the (baseline year + lc scenario0)

func_calculate_change_from_yri_lc0 <- function(
    data = shp_all_df,
    return_sf = FALSE
) {

  df_change <- data %>%
    rename('value' = ind) %>%
    mutate(value = value * ind_scale) %>%
    group_by(year) %>%
    mutate(value_diff = value - value[lc_scenario == "scenario0"]) %>%
    mutate(year = as.numeric(year)) %>%
    filter(year >= year_baseline) %>%
    filter(lc_scenario != "scenario0") %>%
    as.data.frame() 
  
  
  # df_change_check <- shp_all_df %>%
  #   rename('value' = ind) %>%
  #   mutate(value = value * ind_scale) %>%
  #   select(1:2, value, lc_scenario, year) %>%
  #   pivot_wider(names_from = lc_scenario, values_from = value) %>%
  #   mutate(val_d_420 = scenario4_20 - scenario0, 
  #          val_d_430 = scenario4_20 - scenario0)
  # 
  # df_change_check_summ <- 
  #   df_change_check %>%
  #   dplyr::group_by(year) %>%
  #   dplyr::summarise(
  #     n = sum(!is.na(val_d_420)),
  #     mean = mean(val_d_420, na.rm = TRUE),
  #     mean_sig12 = signif(mean, 12),
  #     sd = sd(val_d_420, na.rm = TRUE)
  #   )
  
  
  
  
  df_chg_sf_i0 <- df_change %>%
    select(GSS_CODE, year, lc_scenario, value_diff) %>%
    mutate(var = ind) %>%
    left_join(aoi, ., by = 'GSS_CODE')
  
  
  df_stats_i0 <- df_change %>%
    group_by(year, lc_scenario) %>%
    dplyr::summarise(
      value_diff_mean = mean(value_diff, na.rm = TRUE),  # group mean
      sd = sd(value_diff, na.rm = TRUE),                 # standard deviation
      n  = n(),                                          # sample size
      se = sd / sqrt(n),                                 # standard error
      ci_lower = value_diff_mean - 1.96 * se,
      ci_upper = value_diff_mean + 1.96 * se, 
      .groups = "drop"
    ) %>%
    as.data.frame()
  
  return(df_stats_i0)
  ## which plot to show in the window
  return(if (isTRUE(return_sf)) df_chg_sf_i0 else df_stats_i0)
  
}


df_stats_i0 <- func_calculate_change_from_yri_lc0(data = shp_all_df)
df_chg_sf_i0<- func_calculate_change_from_yri_lc0(data = shp_all_df, return_sf = T)
```



```{r - stats: change from yr 0 + lc 0}

## compare to the (baseline year + lc scenario0)

func_calculate_change_from_yr0_lc0 <- function(
    data = shp_all_df
) {
  
  df_i <- data %>%
    rename('value' = ind) %>%
    mutate(value = value * ind_scale,
           climate_lc = paste0(year, "_", lc_scenario))
  
  # 1) compute baseline per feature (2020, scenario0)
  df_base <- df_i %>%
    filter(year == year_baseline, lc_scenario == "scenario0") %>%
    select(GSS_CODE, 
           # NAME, id, year, lc_scenario, climate_lc, 
           baseline = value) # <-- use your feature key here (e.g., id/borough)
  
  # 2) join and compute differences for all rows
  df_change_00 <- df_i %>%
    left_join(df_base, by = "GSS_CODE") %>%        # join baseline per feature
    mutate(value_diff = value - baseline) %>%
    select(-baseline) %>%
    # filter(climate_lc != paste0(year_baseline, "_scenario0")) %>%
    as.data.frame() 
  
  
  df_change_00_sf <- df_change_00 %>%
    select(GSS_CODE, year, lc_scenario, value_diff) %>%
    mutate(var = ind) %>%
    left_join(aoi, ., by = 'GSS_CODE')
  
  
  df_stats_00 <- df_change_00 %>%
    group_by(year, lc_scenario) %>%
    dplyr::summarise(
      value_diff_mean = mean(value_diff, na.rm = TRUE),  # group mean
      sd = sd(value_diff, na.rm = TRUE),                 # standard deviation
      n  = dplyr::n(),                                   # sample size
      se = sd / sqrt(n),                                 # standard error
      ci_lower = value_diff_mean - 1.96 * se,
      ci_upper = value_diff_mean + 1.96 * se, 
      .groups = "drop"
    ) %>%
    as.data.frame()
  
  return(df_stats_00)

}



df_stats_00 <- func_calculate_change_from_yr0_lc0(data = shp_all_df)
```





```{r - both --- }

func_combine_two_change_dfs <- function(
  df_stats_00,
  df_stats_i0
){

  stat_00 <- df_stats_00 %>%
    select(year, lc_scenario, chg = value_diff_mean, ci_lower, ci_upper) %>%
    mutate(year = as.factor(year)) %>%
    mutate(label = 'climate+lc effect')
  
  
  stat_i0 <- df_stats_i0 %>% 
    select(year, lc_scenario, chg = value_diff_mean, ci_lower, ci_upper) %>%
    mutate(year = as.factor(year)) %>%
    mutate(label = 'lc effect')
  
  
  stat_both <- stat_00 %>%
    filter(lc_scenario != "scenario0") %>%
    rename(chg_0 = chg) %>%
    left_join(stat_i0 %>% rename(chg_i = chg), 
              by = c('year', 'lc_scenario'))
  
  
  stat_both_l <- rbind(stat_00, stat_i0) %>%
    filter(!year %in% c('2020')) %>%
    group_by(year) %>%
    arrange(year, lc_scenario)
  
  return(stat_both_l)
  
  }


## apply the function 
stat_both_l <- func_combine_two_change_dfs(df_stats_00, df_stats_i0)



# reference values from scenario0
base_lines <- stat_both_l %>%
  dplyr::filter(lc_scenario == "scenario0") %>%
  dplyr::transmute(label, year, y0 = chg)

base_segments <- base_lines %>%
  dplyr::mutate(
    year = as.numeric(year), 
    xmin = year - 3, 
    xmax = year + 3)

stat_both_l %>%
  # dplyr::mutate(year = as.numeric(year) ) %>%
  ggplot(aes(x = year, y = chg, 
             group = interaction(year, lc_scenario),
             color = lc_scenario
             )) +
  geom_point(aes(shape = label), size = 2.5, 
             position = position_dodge(width = 0.9),
             # position = position_dodge2(width = 0.75, padding = 0.1, preserve = "single"),

             stroke = 1, 
             alpha = .7) +
  facet_wrap(~label, scale = 'free_y') + 
  
  scale_color_manual(
    values = scenario_colors,
    name = "Land Scenario"
  ) +
  
  scale_shape_manual(values = c('climate+lc effect' = 1, 'lc effect' = 2), guide = "none") +
  guides(fill = "none") + 

  labs(
      x = "Year",
      y = str_to_title(paste0(ind_label, " change")),
    ) +
  
  theme_bw() +
  theme(
      legend.position = c(0.1, 0.8),
      legend.spacing.y  = unit(0.05, "cm"),
      legend.key.height = unit(0.05, "cm"), 
      legend.key.width = unit(0.05, "cm"),
      legend.background = element_rect(fill = "transparent", color = NA),
      legend.key = element_rect(fill = "transparent", color = NA),
      panel.grid.minor = element_blank()
    ) 

f <- file.path(dir.fig, paste("temp_scenarios_fromshp", "line_dif", ind, 'both', ymd, "1.png", sep = '_'))
func_ggsave(f, w = 7, h = 5, dpi = 300, save_png = T)
```


```{r - both 2, eval=FALSE, include=FALSE}

library(dplyr)
library(ggplot2)

# 1) Discrete x for plotting
levels_year <- sort(unique(stat_both_l$year))
dat <- stat_both_l %>% mutate(year_f = factor(year, levels = levels_year))

# 2) Short horizontal ticks for scenario0 (compute numeric centers just for segments)
base_segments <- dat %>%
  filter(lc_scenario == "scenario0") %>%
  mutate(
    x_idx = as.integer(factor(year, levels = levels_year)),  # 1..n
    xmin  = x_idx - 0.5,
    xmax  = x_idx + 0.5,
    y0    = chg
  )

ggplot(dat, aes(x = year_f, y = chg,
                group = interaction(year_f, lc_scenario),
                color = lc_scenario)) +
  geom_segment(
    data = base_segments,
    aes(x = xmin, xend = xmax, y = y0, yend = y0),
    position = position_dodge(width = 0.9), 
    inherit.aes = FALSE,
    # linetype = "dotted", 
    linewidth = 0.5, color = "grey30"
  ) +
  geom_point(aes(shape = label), 
             position = position_dodge(width = 0.9),
             size = 2.5, stroke = 1, alpha = .7) +
  facet_wrap(~ label, scales = "free_y") +
  scale_color_manual(values = scenario_colors, name = "Land Scenario") +
  scale_shape_manual(values = c('climate+lc effect' = 1, 'lc effect' = 2), guide = "none") +
  scale_x_discrete(drop = FALSE) +   # <-- explicitly force discrete x
  theme_bw() +
  theme(
      legend.position = c(0.1, 0.8),
      legend.spacing.y  = unit(0.01, "cm"),
      legend.key.height = unit(0.08, "cm"), 
      legend.background = element_rect(fill = "transparent", color = NA),
      legend.key = element_rect(fill = "transparent", color = NA),
      panel.grid.minor = element_blank()
    ) 

f <- file.path(dir.fig, paste("temp_scenarios_fromshp", "line_dif", ind, 'both', ymd, "-2.png", sep = '_'))
func_ggsave(f, w = 7, h = 5, dpi = 300, save_png = T)

```

```{r - one - lc+climate}

stat_both_l %>%
  filter(label == 'climate+lc effect') %>%
  filter(!(year == year_baseline & lc_scenario != "scenario0")) %>%
  ggplot(aes(x = year, 
             y = chg, 
             group = interaction(year, lc_scenario),
             color = lc_scenario
             )) +
  geom_point(size = 2.5, 
             shape = 1, 
             position = position_dodge(width = 0.9),
             fill = NA, 
             stroke = 1, 
             alpha = .7) +
  
  # geom_line(
  #   position = position_dodge(width = 0.9), show.legend = F,
  # ) +

  scale_color_manual(
    values = scenario_colors,
    name = "Land Scenario"
  ) +
  
  guides(fill = "none", shape = 'none') + 

  labs(
      x = "Year",
      y = str_to_title(paste0(ind_label, " change")),
    ) +
  
  theme_bw() +
  theme(
      legend.position = c(0.2, 0.85),
      legend.spacing.y  = unit(0.05, "cm"),
      legend.key.height = unit(0.05, "cm"), 
      legend.key.width = unit(0.05, "cm"),
      legend.background = element_rect(fill = "transparent", color = NA),
      legend.key = element_rect(fill = "transparent", color = NA),
      panel.grid.minor = element_blank()
    ) 

f <- file.path(dir.fig, paste("temp_scenarios_fromshp", "line_dif", ind, 'both01', ymd, ".png", sep = '_'))
func_ggsave(f, w = 7/2, h = 5, dpi = 300, save_png = T)

```



```{r - one - lc}

func_plot_change_point <- function(data, plot_avg = FALSE){

  stat_chg_per_lc_yr <- 
    data %>%
    ungroup() %>%
    filter(label == 'lc effect') %>%
    filter(year != year_baseline) %>%
    mutate(chg_direction = ifelse(chg>=0, 'inc', 'dec')) %>%
    mutate(lc_scenario = factor(lc_scenario, levels = unique(lc_scenario))) 
  
  
  p1 <- 
    stat_chg_per_lc_yr %>%
    ggplot(aes(x = year, 
               y = chg, 
               group = interaction(year, lc_scenario),
               color = lc_scenario
               )) +
    geom_point(
      aes(shape = chg_direction),
      size = 2.5, 
      position = position_dodge(width = 0.9),
      fill = NA, 
      stroke = 1, 
      alpha = .7) +
    
    # geom_errorbar(
    #   aes(ymin = ci_lower, ymax = ci_upper),
    #   width = 0.1, alpha = 0.5, 
    #   position = position_dodge(width = 0.9)
    # ) +
    # 
    
    geom_text(
        aes(label = sprintf("%+.2f", chg)),
        position = position_dodge(width = 0.9),
        hjust = -0.2,
        size = 3, show.legend = F,
        fontface = "bold"
      ) +
    
    geom_hline(yintercept = 0, linetype = 'dashed', colour = 'gray', show.legend = FALSE) +
   
    
    facet_wrap(~year, scales = 'free_x', ncol = 2) + 
  
    scale_color_manual(
      values = scenario_colors,
      name = "Land Scenario"
    ) +
    scale_shape_manual(values = c('inc' = 2, 'dec' = 6), guide = "none") +
    guides(fill = "none", 
           # guide_legend(override.aes = ...) ensures the legend shows hollow points (matching fill = NA)
           color = guide_legend(override.aes = list(shape = 6, fill = NA, size = 2, stroke = 0.5, alpha = 1)),
           shape = 'none') + 
  
    labs(x = "Year",y = str_to_title(paste0(ind_label, " change"))) +
    ## This allows plot elements (like text) to extend beyond the plot panel boundaries without being clipped
    coord_cartesian(clip = "off") + 
    theme_bw() +
    theme(
      axis.title.x = element_blank(),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(), 
      panel.border = element_rect(fill = "transparent", color = 'gray30', linewidth=0.2),
      strip.background = element_rect(color = "gray30", linewidth = 0.2),
      
      legend.position = c(0.8, 0.25),
      legend.spacing.y  = unit(0.05, "cm"),
      # legend.key.height = unit(0.05, "cm"), 
      # legend.key.width = unit(0.03, "cm"),
      legend.key.size = unit(1, "pt"),
      
      legend.background = element_rect(fill = "transparent", color = NA),
      legend.key = element_rect(fill = "transparent", color = NA),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank()
      ) 
  p1
  f <- file.path(dir.fig, paste("temp_scenarios_fromshp", "line_dif", ind, 'both02', ymd, ".png", sep = '_'))
  func_ggsave(f, w = 7/2, h = 5, dpi = 300, save_png = T)
  

  
  ## ------------------------------------------------------------------------ ##
  stat_chg_avg <- stat_chg_per_lc_yr %>%
    group_by(lc_scenario, label) %>%
    summarise_if(is.numeric, mean, na.rm = TRUE) %>%
    ## add a place holder
    mutate(year = 'year')
    
  p2 <- 
    stat_chg_avg %>%
    ggplot(aes(x = year, 
               y = chg, 
               group = lc_scenario,
               color = lc_scenario
               )) +
    # geom_point(
    #   aes(shape = chg_direction),
    #   size = 2.5, 
    #   position = position_dodge(width = 0.9),
    #   fill = NA, 
    #   stroke = 1, 
    #   alpha = .7) +
    # scale_shape_manual(values = c('inc' = 2, 'dec' = 6), guide = "none") +
    
    geom_col(
      # position = position_dodge(width = 0.9),
      position = position_dodge2(width = 0.9, padding = 0.2),
      fill = 'gray80', 
      alpha = .7
    ) +
    
    geom_text(
        aes(label = sprintf("%+.2f", chg)),
        position = position_dodge(width = 0.9),
        # hjust = -0.2, # if using geom_point
        vjust = -0.5,
        size = 3, show.legend = F,
        fontface = "bold"
      ) +
    
    geom_hline(yintercept = 0, linetype = 'dashed', colour = 'gray', show.legend = FALSE) +
   
    scale_color_manual(
      values = scenario_colors,
      name = "Land Scenario"
    ) +
    
    guides(fill = "none", 
           color = guide_legend(override.aes = list(shape = 6, fill = NA, size = 2, stroke = 0.5, alpha = 1)),
           shape = 'none') + 
  
    labs(x = "",y = str_to_title(paste0(ind_label, " change"))) +
    ## This allows plot elements (like text) to extend beyond the plot panel boundaries without being clipped
    coord_cartesian(clip = "off") + 
    theme_bw() +
    theme(
      # axis.title.x = element_blank(),
      # axis.text.x = element_blank(),
      axis.text.x = element_text(color = "transparent"), 
      axis.ticks.x = element_blank(), 
      panel.border = element_rect(fill = "transparent", color = 'gray30', linewidth=0.2),
      strip.background = element_rect(color = "gray30", linewidth = 0.2),
      
      # legend.position = c(0.8, 0.9),
      legend.position = 'none',
      legend.spacing.y  = unit(0.05, "cm"),
      legend.key.size = unit(1, "pt"),
  
      legend.background = element_rect(fill = "transparent", color = NA),
      legend.key = element_rect(fill = "transparent", color = NA),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank()
      ) 
  f <- file.path(dir.fig, paste("temp_scenarios_fromshp", "line_dif", ind, 'both03', ymd, ".png", sep = '_'))
  ggsave(filename = f, plot = p2, width = 7/2, height = 5, dpi = 300)
  
  
  ## which plot to show in the window
  return(if (isTRUE(plot_avg)) p2 else p1)

}



func_plot_change_point(data = stat_both_l)
```


  As the change due to lc are almost the same, we only need to present one figure using the averaged value. 
  
```{r - one - lc - avg}

func_plot_change_point(data = stat_both_l, plot_avg = T)

```


```{r - plot - facet by year}

n_year <- length(unique(df_summary_fromshp$year))

if (n_year<5) {
  fig_h <- 2.5
} else {
  fig_h <- 2.5*ceiling(n_year/4)
}

# Bar plot with error bars
df_summary_fromshp %>%
  ggplot(., aes(x = lc_scenario, y = mean, fill = mean)) +
  geom_col(position = position_dodge(width = 0.9), alpha = 0.7, show.legend = F) +
  geom_errorbar(
    aes(ymin = mean - sd, ymax = mean + sd),
    width = 0.2, alpha = 0.5, 
    position = position_dodge(width = 0.9)
  ) +
  scale_fill_distiller(name = "Temp (°C)", palette = "OrRd", oob = scales::squish, direction = 1) +
  
  # add mean values as text labels
  geom_text(
    aes(label = round(mean, 1), y = mean),   # label from mean
    vjust = -0.5,                            # push above bar
    color = 'red',
    size = 2                                 # adjust font size
  ) +
  # facet_wrap(~ year, scale = 'free_x') + 
  facet_wrap(~ year, scale = 'free', ncol = 4) +
  labs(
    x = "Land Cover Scenario",
    y = "Mean Value ± SD",
    # fill = "year"
  ) +
  # scale_fill_brewer(palette = "Set2", direction = 1) +  # reverse order
  theme_bw() +
  coord_cartesian(ylim = c(20, NA)) +   # start at 20, let top auto-scale
  scale_y_continuous(expand = c(0, 1)) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )


# Save your last ggplot as PNG
f <- file.path(dir.fig, paste0("temp_scenarios_fromshp_", ind, '_facetYear_', ymd, ".png"))
ggsave(filename = f, width = 7, height = fig_h, units = 'in', dpi = 300)

```

```{r - plot - facet by scenario}

# Bar plot with error bars
df_summary_fromshp %>%
  ggplot(., aes(x = year, y = mean, fill = mean)) +
  geom_col(position = position_dodge(width = 0.9), 
           alpha = 0.7, show.legend = F) +
  geom_errorbar(
    aes(ymin = mean - sd, ymax = mean + sd),
    width = 0.2, alpha = 0.5, 
    position = position_dodge(width = 0.9)
  ) +
  
  # add mean values as text labels
  geom_text(
    aes(label = round(mean, 1), y = mean),   # label from mean
    vjust = -0.5,                            # push above bar
    color = 'red',
    size = 2                                 # adjust font size
  ) +
  scale_fill_distiller(name = "Temp (°C)", palette = "OrRd", oob = scales::squish, direction = 1) +
  # scico::scale_fill_scico(name = "Temp (°C)", palette = "lajolla", direction = -1, end = 0.8) + 
  facet_wrap(~ lc_scenario, 
             # scale = 'free', 
             ncol = 4) +
  labs(
    x = "Year",
    y = "Mean ± SD",
  ) +
  # scale_fill_brewer(palette = "Set2", direction = 1) +  # reverse order
  theme_bw() +
  coord_cartesian(ylim = c(20, NA)) +   # start at 20, let top auto-scale
  scale_y_continuous(expand = c(0, 1.5)) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )


# Save your last ggplot as PNG
f <- file.path(dir.fig, paste0("temp_scenarios_fromshp_", ind, '_facetLULC_', ymd, ".png"))
ggsave(
  filename = f,   # file name
  width    = 7,                    # width in inches
  height   = 4,                    # height in inches
  units = 'in',
  dpi      = 300                   # resolution (good for PPT/publications)
)

```




```{r - heatmap, eval=FALSE, include=FALSE}

# install.packages(c("dplyr","tidyr","ggplot2","scico","forcats"))
library(dplyr)
library(tidyr)
library(ggplot2)
library(scico)
library(forcats)

# --- 1) Prep (aggregate if needed, complete full grid, order axes) ---
df_grid <- df_summary_fromshp %>%
  # group_by(year, lc_scenario) %>%
  # summarize(temp_c = mean(temp_c, na.rm = TRUE), .groups = "drop") %>%
  rename('temp_c' = 'mean') %>%
  # ensure a full 4x5 grid (so missing combos plot as NA tiles)
  complete(year, lc_scenario) %>%
  # mutate(
  #   year = factor(year, levels = sort(unique(year))),  # x order left→right
  #   # order scenarios by their mean temperature (high→low); remove .desc=TRUE to reverse
  #   lc_scenario = fct_reorder(lc_scenario, temp_c, .fun = mean, .na_rm = TRUE, .desc = TRUE)
  # ) %>%
  as.data.frame()

# --- 2) Plot: color grid heatmap ---
p <- ggplot(df_grid, aes(x = year, y = lc_scenario, fill = temp_c)) +
  geom_tile(color = "white", linewidth = 0.4, na.rm = FALSE) +
  scico::scale_fill_scico(
    name = "Temp (°C)",
    palette = "lajolla",          # nice warm sequential; try "batlow" or "oslo" too
    na.value = "grey90"
  ) +
  labs(x = "Year", y = "Land-cover scenario",
       title = "Temperature by Year and Land-cover Scenario") +
  theme_minimal(base_size = 11) +
  theme(
    panel.grid = element_blank(),
    axis.title.y = element_text(margin = margin(r = 6)),
    axis.title.x = element_text(margin = margin(t = 6))
  )

p
```


```{r - heatmap - grid, eval=FALSE, include=FALSE}

library(ggplot2)

ggplot(df_grid, aes(x = year, y = temp_c, fill = temp_c)) +
  geom_col(width = 0.85, colour = 'gray') +
  facet_grid(rows = vars(lc_scenario), switch = "y") +
  # scale_fill_viridis_c(name = "Temp (°C)", option = "C") +
  scale_fill_distiller(name = "Temp (°C)", palette = "OrRd", oob = scales::squish, direction = 1) +
  scale_y_continuous(position = "right") + # <- move y-axis labels/ticks to the right
  coord_cartesian(ylim = c(20, NA)) +   # start at 20, let top auto-scale
  labs(x = "Year", y = NULL, title = "Temperature by Year and Scenario") +
  theme_minimal(base_size = 11) +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
        strip.text.y.right = element_text(angle = 0, margin = margin(l = 6)), # right-side labels
        # strip.text.y.left = element_text(angle = 0),
        # strip.placement = "outside",
        legend.position = "right")

# Save your last ggplot as PNG
f <- file.path(dir.fig, paste0("temp_scenarios_fromshp_", ymd, "_grid.png"))
ggsave(
  filename = f,   # file name
  width    = 7,                    # width in inches
  height   = 8,                    # height in inches
  units = 'in',
  dpi      = 300                   # resolution (good for PPT/publications)
)
```

```{r - test, eval=FALSE, include=FALSE}

library(ggplot2)
library(dplyr)

# Assuming your data is in a dataframe called 'df'
# If you need to read it in, use: df <- read.csv("your_file.csv")

# Create the plot
ggplot(df_grid, aes(x = year, y = temp_c, color = lc_scenario, group = lc_scenario)) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 3, alpha = 0.7) +
  scale_color_manual(
    values = c(
      "scenario0" = "#FED976",
      "scenario1" = "#FEB24C", 
      "scenario2" = "#FD8D3C",
      "scenario3" = "#FC4E2A",
      "scenario4_10" = "#E31A1C",
      "scenario4_20" = "#BD0026",
      "scenario4_30" = "#800026"
    ),
    name = "Scenario"
  ) +
  labs(
    title = "Temperature Projections by Scenario",
    subtitle = "Comparing trends across different climate scenarios",
    x = "Year",
    y = "Temperature (°C)",
    caption = "Note: Darker colors indicate more severe scenarios"
  ) +
  # scale_x_continuous(breaks = c(20.2, 22.2, 25.5, 28.5)) + 
  
  # # Optional: Add confidence intervals using the 'sd' column
  # # Uncomment the following to add shaded ribbons:
  # geom_ribbon(aes(ymin = temp_c - sd, ymax = temp_c + sd, fill = lc_scenario),
  #               alpha = 0.2,show.legend = F, color = NA) + 
  theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(color = "gray40", margin = margin(b = 15)),
    legend.position = "right",
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_line(linetype = "dashed", linewidth = 0.3),
    axis.title = element_text(face = "bold")
  ) 


# Save your last ggplot as PNG
f <- file.path(dir.fig, paste0("temp_scenarios_fromshp_", ymd, "_line.png"))
ggsave(
  filename = f,   # file name
  width    = 7,                    # width in inches
  height   = 8,                    # height in inches
  units = 'in',
  dpi      = 300                   # resolution (good for PPT/publications)
)
```



```{r - test 2, eval=FALSE, include=FALSE}

library(ggplot2)
library(dplyr)

# Assuming your data is in a dataframe called 'df'

df = df_grid

# Option 1: Faceted plot by year to see scenario differences clearly
p1 <- df_grid %>%
  ggplot(., aes(x = lc_scenario, y = temp_c, fill = lc_scenario)) +
  geom_col() +
  facet_wrap(~year, scales = "free_x", nrow = 1) +
  scale_fill_manual(
    values = c(
      "scenario0" = "#FED976",
      "scenario1" = "#FEB24C", 
      "scenario2" = "#FD8D3C",
      "scenario3" = "#FC4E2A",
      "scenario4_10" = "#E31A1C",
      "scenario4_20" = "#BD0026",
      "scenario4_30" = "#800026"
    )
  ) +
  labs(
    title = "Temperature by Scenario and Year",
    subtitle = "Each panel shows scenario comparison for a specific year",
    x = "Scenario",
    y = "Temperature (°C)"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(color = "gray40", margin = margin(b = 15)),
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1, size = 9),
    strip.text = element_text(face = "bold", size = 11),
    panel.spacing = unit(1, "lines")
  )




# Option 2: Show the differences from a baseline (scenario0)
df_diff <- df %>%
  group_by(year) %>%
  mutate(temp_diff = temp_c - temp_c[lc_scenario == "scenario0"]) %>%
  filter(lc_scenario != "scenario0")

p2 <- ggplot(df_diff, aes(x = year, y = temp_diff, color = lc_scenario, group = lc_scenario)) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 3) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
  scale_color_manual(
    values = c(
      "scenario1" = "#FEB24C", 
      "scenario2" = "#FD8D3C",
      "scenario3" = "#FC4E2A",
      "scenario4_10" = "#E31A1C",
      "scenario4_20" = "#BD0026",
      "scenario4_30" = "#800026"
    ),
    name = "Scenario"
  ) +
  labs(
    title = "Temperature Difference from Baseline (Scenario 0)",
    subtitle = "Highlighting how each scenario diverges from the baseline",
    x = "Year",
    y = "Temperature Difference (°C)",
    caption = "Positive values indicate higher temperatures than scenario0"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(color = "gray40", margin = margin(b = 15)),
    legend.position = "right",
    panel.grid.minor = element_blank()
  ) 


# Option 3: Faceted by scenario to see individual trends
p3 <- df_grid %>%
  ggplot(., aes(x = year, y = temp_c)) +
  geom_line(linewidth = 1, color = "#E31A1C") +
  geom_point(size = 2.5, color = "#E31A1C") +
  facet_wrap(~lc_scenario, ncol = 4) +
  labs(
    title = "Temperature Trends by Individual Scenario",
    subtitle = "Each panel shows temperature progression for one scenario",
    x = "Year",
    y = "Temperature (°C)"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(color = "gray40", margin = margin(b = 15)),
    strip.text = element_text(face = "bold", size = 10),
    panel.grid.minor = element_blank()
  ) 


# Display the plots (choose one or compare)
p1  # Bar chart by year
p2  # Difference from baseline (RECOMMENDED)
p3  # Small multiples by scenario

```




```{r - test 3, eval=FALSE, include=FALSE}
library(ggplot2)
library(dplyr)



# Option 2: Show the differences from a baseline (scenario0)
df_diff <- df %>%
  group_by(year) %>%
  mutate(temp_diff = temp_c - temp_c[lc_scenario == "scenario0"]) %>%
  filter(lc_scenario != "scenario0")

p2 <- ggplot(df_diff, aes(x = year, y = temp_diff, color = lc_scenario, group = lc_scenario)) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 3) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray60") +
  scale_color_manual(
    values = c(
      "scenario1" = "#d95f0e", # #78C679
      "scenario2" = "#41AB5D", 
      "scenario3" = "#fec44f",
      "scenario4_10" = "#238B45",
      "scenario4_20" = "#006D2C",
      "scenario4_30" = "#002910"
    ),
    name = "Greening Scenario",
    labels = c("scenario1" = "Scenario 1",
               "scenario2" = "Scenario 2",
               "scenario3" = "Scenario 3",
               "scenario4_10" = "Scenario 4_10",
               "scenario4_20" = "Scenario 4_20",
               "scenario4_30" = "Scenario 4_30")
  ) +
  geom_text(
    data = df_diff %>% filter(year == '28_5'),
    aes(label = sprintf("%+.2f°C", temp_diff)),
    hjust = -0.2,
    size = 3.5, show.legend = F,
    fontface = "bold"
  ) +
  labs(
    title = "Temperature Difference from Baseline (Scenario 0)",
    subtitle = "Greening scenarios compared to baseline - darker green indicates more greening",
    x = "Year",
    y = "Temperature Difference (°C)",
    caption = "Positive values indicate higher temperatures than scenario0"
  ) +
  theme_minimal(base_size = 10) +
  theme(
    plot.title = element_text(face = "bold", size = 12),
    plot.subtitle = element_text(color = "gray40", margin = margin(b = 10)),
    # legend.position = "right",
    legend.position = c(0.21, 0.81),
    legend.spacing.y = unit(0.02, "cm"),
    legend.key.height = unit(0.4, "cm"),
    panel.grid.minor = element_blank()
  ) 


# Display the plots (choose one or compare)
# p1  # Bar chart by year
p2  # Difference from baseline (RECOMMENDED)
# p3  # Small multiples by scenario

f <- file.path(dir.fig, paste0("temp_scenarios_fromshp_", ymd, "_line_dif.png"))
print(f)
func_ggsave(f, w = 7, h = 6, save_png = T)
```








```{r - func_plot_line}

# install.packages("ggbreak")
library(ggbreak)

func_plot_line <- function(
    data, 
    legend.position.y = 0.21, 
    y_break = NA,  # the gap to skip, `space` controls the visual notch size.
    yr_label = '2070'         # the year to add value label 
    ){
  
  df_stats <- data

  p <- df_stats %>%
    ggplot(., aes(x = year, y = value_diff_mean, 
                  color = lc_scenario, 
                  fill = lc_scenario, 
                  group = lc_scenario)) +
    geom_ribbon(aes(ymin = ci_lower, ymax = ci_upper), alpha = 0.25, color = NA) +
    geom_line(linewidth = 1.2) +
    geom_point(size = 3) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "gray60") +
    scale_color_manual(
      # # remove the "scenario0" color from the named vector
      values = scenario_colors[names(scenario_colors) != "scenario0"],
      name = "Greening Scenario",
      # labels = c("scenario1" = "Scenario 1",
      #            "scenario2" = "Scenario 2",
      #            "scenario3" = "Scenario 3",
      #            "scenario4_10" = "Scenario 4_10",
      #            "scenario4_20" = "Scenario 4_20",
      #            "scenario4_30" = "Scenario 4_30")
    ) +
    scale_fill_manual(
      values = scenario_colors[names(scenario_colors) != "scenario0"],
      guide = "none"
    ) +
    geom_text(
      data = df_stats %>% 
        filter(year == yr_label),
      aes(label = sprintf("%+.2f", value_diff_mean)),
      hjust = -0.2,
      size = 3.5, show.legend = F,
      fontface = "bold"
    ) +
    labs(
      title = paste0(str_to_sentence(ind_label), " difference from baseline (Scenario 0)"),
      subtitle = "Greening scenarios compared to baseline - darker green indicates more greening",
      x = "Year",
      y = paste0(ind_label, " change"),
      caption = "Shaded areas represent 95% confidence intervals (±1.96 SE)"
    ) +
    ## This allows plot elements (like text) to extend beyond the plot panel boundaries without being clipped
    coord_cartesian(clip = "off") + 
    theme_minimal(base_size = 10) +
    theme(
      plot.title = element_text(face = "bold", size = 12),
      plot.subtitle = element_text(color = "gray40", margin = margin(b = 10)),
      plot.margin = margin(r = 1, unit = "cm"),
      # legend.position = "right",
      legend.position = c(0.21, legend.position.y),
      legend.spacing.y = unit(0.02, "cm"),
      legend.key.height = unit(0.4, "cm"),
      panel.grid.minor = element_blank()
    ) 
  
  if (!is.na(y_break)) {
    p <- p + ggbreak::scale_y_break(y_break, space = 0.02)
  }
  
  print(p)
  
  ## save figure
  f <- file.path(dir.fig, paste0("temp_scenarios_fromshp_", "line_dif_", ind, '_', ymd, ".png"))
  print(f)
  func_ggsave(f, w = 7, h = 6, save_png = T)

}

```



```{r - func_plot_map}

func_plot_map <- function(data) {
  
  # Apply to your data and plot
  scale_params <- get_color_scale(data$value_diff)
  
  p <- ggplot(data = data) +
    geom_sf(aes(fill = value_diff), color = NA, size = 0.1)
  
  
  # customize colors for temperature change 
  if (ind == 'avg_tmp_v') {
    scale_params_colors <- rev(scale_params$colors)
  } else {
    scale_params_colors <- scale_params$colors
  }
  
  # Apply appropriate scale based on data
  if (scale_params$scale_type == "diverging") {
    p <- p + 
      scale_fill_gradientn(
        colors = scale_params_colors,
        limits = c(scale_params$vmin, scale_params$vmax),
        values = scales::rescale(c(scale_params$vmin, 0, scale_params$vmax)),
        name = "Change",
        na.value = "grey90",
        oob = scales::squish
      )
  } else {
    p <- p +
      scale_fill_gradientn(
        colors = scale_params$colors,
        limits = c(scale_params$vmin, scale_params$vmax),
        name = "Change",
        na.value = "grey90",
        oob = scales::squish
      )
  }
  
  p <- p +
    facet_grid(lc_scenario~year, switch = "y") +
    theme_minimal() +
    theme(
      axis.text = element_blank(),
      axis.ticks = element_blank(),
      panel.grid = element_blank(),
      strip.text = element_text(size = 10, face = "bold"),
      strip.text.y.left = element_text(
        angle = 45, 
        margin = margin(l = 6, r = 4), # Tip: if labels clip, add a little space
        hjust = 0.5, vjust = 0.5),
      legend.position = "right",
      legend.key.width = unit(.5, "cm")
    ) +
    labs(
      title = paste(str_to_title(ind_label), 'change attributable to land use'), 
      subtitle = '(climate held constant, same year)'
    )
  
  print(p)
  
  
  f <- file.path(dir.fig, paste0("temp_scenarios_fromshp_", "map_dif_", ind, '_', ymd, ".png"))
  print(f)
  func_ggsave(f, w = 7, h = 7, dpi = 500, save_png = T)

}

```


```{r - plot - line}

df_stats_input <- df_stats_i0 %>% 
  filter(!year %in% c('2020')) %>%
  mutate(year = as.factor(year)) %>%
  as.data.frame()

func_plot_line(data = df_stats_input, legend.position.y = 0.81, y_break = NA, yr_label = '2070')

```





```{r - plot - map}

df_chg_sf_i0_input <- df_chg_sf_i0 %>% 
  filter(year > year_baseline) %>%
  mutate(year = as.factor(year)) 

func_plot_map(data = df_chg_sf_i0_input)

```




```{r - dunns test, eval=FALSE, include=FALSE}

source('./code/func_comparing_means_Dunns.R')

text_size = 10

## run 2 -- an updated function 
which_test = 'dunn'
which_test = 'wilcoxon'
func_test_dif_dunn2(df = df_summary_fromshp, 
                    value = 'mean', 
                    group = 'lc_scenario', 
                    which_test, ## "dunn" or "wilcoxon",
                    out_dir = file.path(dir_ucm_out, 'ucm_output_postprocess'),
                    facet_by = 'year',
                    tag = "uhi_results_combined"
                    )
f <- file.path(dir.fig, paste("temp_scenarios_fromshp", ymd, which_test, ".png", sep = '_'))
print(f)
func_ggsave(f, w = 7, h = 5, save_png = T)
```

