# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.14.1 on Thu Sep 11 15:41:20 2025
# Model: Urban Cooling

import logging
import sys
import numpy as np

import natcap.invest.urban_cooling_model
import natcap.invest.utils

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])

args = {
    'aoi_vector_path': 'G:\\Shared drives\\Wellcome Trust Project '
                       'Data\\1_preprocess\\UrbanCoolingModel\\OfficialWorkingInputs\\AOIs\\London_Borough_aoi.shp',
    'avg_rel_humidity': '',
    'biophysical_table_path': 'G:\\Shared drives\\Wellcome Trust Project '
                              'Data\\1_preprocess\\UrbanCoolingModel\\OfficialWorkingInputs\\LULC\\Biophysical_table_ukech_2021_london_with_TCC.csv',
    'building_vector_path': '',
    'cc_method': 'factors',
    'cc_weight_albedo': '',
    'cc_weight_eti': '',
    'cc_weight_shade': '',
    'do_energy_valuation': False,
    'do_productivity_valuation': False,
    'energy_consumption_table_path': '',
    'green_area_cooling_distance': '450',
    'lulc_raster_path': 'G:\\Shared drives\\Wellcome Trust Project '
                        'Data\\1_preprocess\\UrbanCoolingModel\\OfficialWorkingInputs\\LULC\\LCM2023_London_10m_clip2aoi_tcc24_scenario3_TreeRisk.tif',
    'ref_eto_raster_path': 'G:\\Shared drives\\Wellcome Trust Project '
                           'Data\\1_preprocess\\UrbanCoolingModel\\OfficialWorkingInputs\\evapotranspiration\\et0_V3_07_clipped_reprojected.tif',
    'results_suffix': '',
    't_air_average_radius': '500',
    't_ref': '20',
    'uhi_max': '2',
    'workspace_dir': '',
}


if __name__ == '__main__':
    # create an array with pairs of temps and UHI values
    variables = np.array([[20, 2], [20, 5], [22, 2], [22, 5], [25, 2], [25, 5]])
    climate = ('current', 'future')
    # Loop through current and future scenarios
    for c in climate:
        args['workspace_dir'] = f'G:\\Shared drives\\Wellcome Trust Project Data\\2_postprocess_intermediate\\UCM_official_runs\\scenario3\\{c}_climate'
        print(args['workspace_dir'])
        if c == 'future':
            args['ref_eto_raster_path'] = "G:\\Shared drives\\Wellcome Trust Project Data\\1_preprocess\\UrbanCoolingModel\\OfficialWorkingInputs\\evapotranspiration\\pet_all_modal_2041_2060_07_245_london_clipped.tif"
        else:
            None
        # Loops through the different temperatures and degrees:
        for temp, uhi in variables:
            # set the temperatures and UHI values
            args['t_ref'] = temp
            args['uhi_max'] = uhi
            # set the suffix to have correct temp and uhi
            args['results_suffix'] = f'london_{c}_scenario_{temp}deg_{uhi}uhi'
            natcap.invest.urban_cooling_model.execute(args)