# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.14.1 on Thu Sep 11 15:41:20 2025
# Model: Urban Cooling
# This script will run all scenarios for Camden. 
# Scenarios were given to us by the J&L team.

import logging
import sys
import numpy as np
import os

import natcap.invest.urban_cooling_model
import natcap.invest.utils

path_prefix = sys.argv[1]

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])


args = {
    'aoi_vector_path': os.path.join(path_prefix, '1_preprocess/UrbanCoolingModel/OfficialWorkingInputs/AOIs/borough_level/camden_borough.shp'),
    'biophysical_table_path': os.path.join(path_prefix, '1_preprocess/UrbanCoolingModel/OfficialWorkingInputs/LULC/Biophysical_table_ukech_2021_london_with_TCC.csv'),
    'building_vector_path': os.path.join(path_prefix, '1_preprocess/UrbanCoolingModel/OfficialWorkingInputs/energy_buildings/bld_with_attr_compact_ucm2_camden_clip_500m.shp'),
    'cc_method': 'factors',
    'cc_weight_albedo': '',
    'cc_weight_eti': '',
    'cc_weight_shade': '',
    'do_energy_valuation': True,
    'do_productivity_valuation': True,
    'energy_consumption_table_path': os.path.join(path_prefix, '1_preprocess/UrbanCoolingModel/OfficialWorkingInputs/energy_buildings/_UCM_Energy Consumption Table.csv'),
    'green_area_cooling_distance': '450',
    'lulc_raster_path': '',
    'ref_eto_raster_path': os.path.join(path_prefix, '1_preprocess/UrbanCoolingModel/OfficialWorkingInputs/evapotranspiration/et0_V3_07_clipped_reprojected_camden_clip_1000m.tif'),
    'results_suffix': '',
    't_air_average_radius': '500',
    't_ref': '',
    'uhi_max': '',
    'workspace_dir': os.path.join(path_prefix, '2_postprocess_intermediate/UCM_official_runs/camden_JL_runs'),
}

if __name__ == '__main__':
    # Set the different scenario lulc inputs and scenario name
    scenario_lulc = [('scenario0', 'LULC_Scenario_0.tif')]
    #scenario_lulc = [('scenario0', 'LULC_Scenario_0.tif'),
    #                   ('scenario2',), ('scenario3',),
    #                 ('scenario4',), ('scenario5',), ('scenario7',)]
    # create an array with groups of temps, UHI values and humidity
    variables = np.array([[22, 2, 55], [25, 5, 45]])
    #variables = np.array([[20, 2, 66.9],[20, 5, 66.9], [22, 2, 55],
    #                      [22, 5, 55], [25, 2, 45], [25, 5, 45]])
    # Run each scenario lulc
    for scenario, lulc in scenario_lulc:
        args['lulc_raster_path'] = f'{path_prefix}/1_preprocess/UrbanCoolingModel/OfficialWorkingInputs/LULC/jlg_lc_scenarios_output/{lulc}'
        # Loops through the different temperatures and degrees:
        for temp, uhi, hum in variables:
            # set the temperatures and UHI values
            args['t_ref'] = temp
            args['uhi_max'] = uhi
            args['avg_rel_humidity'] = hum
            # set the suffix to have correct temp and uhi
            args['results_suffix'] = f'camden_{scenario}_{temp}deg_{uhi}uhi_{hum}hum_energy_productivity'
            natcap.invest.urban_cooling_model.execute(args)

