---
title: "Untitled"
author: "Yingjie"
date: "`r Sys.Date()`"
output: html_document
---



## Matching or standardizing tree species names


```{r - rgbif - not useful, eval=FALSE, include=FALSE}
# # install.packages("rgbif", repos="https://dev.ropensci.org") # dev version
# library("rgbif")
# test1.1 <- name_backbone("Platanus occidentalis x orientalis (P. x hispanica)") # get best match in the GBIF backbone
# test1.2 <- name_suggest("Platanus occidentalis x orientalis (P. x hispanica)") # can be useful if you aren't sure which name to use
```




```{r - TNRS - not useful, eval=FALSE, include=FALSE}
library(TNRS)

# First, we'll grab an example dataset containing two columns: row number and scientific name.
fulldata <- tree1_4

head(fulldata, n = 20)

# Note that there are a variety of formats represented here, sometimes including
# scientific name only
# genus only
# family and genus
# family, scientific name, and author

test2 <- TNRS(taxonomic_names = fulldata$submittedName)
```


  https://joelnitta.github.io/taxastand/
  
```{r - taxastand -- X, eval=FALSE, include=FALSE}
# # install.packages("remotes")
# remotes::install_github("joelnitta/taxastand")


library(taxastand)

# Load example reference taxonomy in Darwin Core format
data(filmy_taxonomy)

# Take a look at the columns used by taxastand
head(filmy_taxonomy[c(
  "taxonID", "acceptedNameUsageID", "taxonomicStatus", "scientificName")])

# As a test, resolve a misspelled name
ts_resolve_names("Platanus occidentalis x orientalis (P. x hispanica)", filmy_taxonomy)


ts_resolve_names(
  "Trichomanes bifidum", filmy_taxonomy, 
  match_no_auth = TRUE, match_canon = TRUE, max_dist = 5)


## --> need to install `taxon-tools`, and not useful as tested. 
```




```{r - U.Taxonstand - not useful, eval=FALSE, include=FALSE}
# # github (requires `remotes` or `devtools`)
# devtools::install_github("ecoinfor/U.Taxonstand")

library(U.Taxonstand)

# load the example database (you can creat your own database for specific taxomic groups)
data(databaseExample)


# The input as a dataframe with the columns "SPECIES", "AUTHOR" and/or "RANK"
spExample <- tree1_4 %>%
  select(submittedName) %>%
  rename('NAME' = 'submittedName')

test4 <- U.Taxonstand::nameMatch(spList=spExample, spSource=databaseExample, author = F, max.distance= 1)
head(test4)

## --> only two matched results, not adding much to the results
```



```{r - rotl, eval=FALSE, include=FALSE}

# remotes::install_github("ropensci/rotl")

library(rotl)

test5 <- tnrs_match_names("Platanus occidentalis x orientalis")

```

